services:
  redis-cache:
    image: redis:7.2.4-alpine3.19
    container_name: redis-cache
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 10

  mysql-database:
    image: mysql
    container_name: mysql-database
    build:
      dockerfile: database/Dockerfile
      context: database
    environment:
      - MYSQL_DATABASE=kbo-reserve
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    restart: unless-stopped
